# Generated by Django 4.2.1 on 2023-06-17 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_students', '0003_alter_studentmodel_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='profile_img',
            field=models.FileField(blank=True, null=True, upload_to='students/profiles'),
        ),
    ]
